[package]
name = "git-default-branch"
version = "0.20251108.20"
edition = "2024"

[dependencies]
gix = "0.74.1"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.23.0"
