[package]
name = "git-default-branch"
version = "0.20251109.22"
edition = "2024"

[profile.release]
lto = true
strip = "symbols"

[dependencies]
gix = "0.75.0"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.24.0"
